//! Galileo E5a primary (LFSR-generated) and secondary spreading codes.
//!
//! The E5a-I (data) and E5a-Q (pilot) primary codes are length-10230 truncated,
//! combined M-sequences generated by a pair of 14-bit LFSRs per the Galileo OS
//! SIS ICD (Issue 2.1, §3.3-3.4): base register 1 (all-ones start) XOR base
//! register 2 (per-PRN start). Feedback taps (Table 15) and base-register-2 start
//! values (Table 16 E5a-I / Table 17 E5a-Q) are factual constants of the
//! signal-in-space standard, transcribed here like the E1 memory codes in
//! [`crate::galileo_e1_codes`]. Correctness is pinned by the ICD's published
//! first-24-chip hex for every PRN (see the tests) -- the test-vector net that
//! catches any transcription or LFSR-convention error.
//!
//! Secondary (tiered) codes: E5a-I overlays the common length-20 CS20 sequence;
//! E5a-Q overlays a per-PRN length-100 CS100 sequence (ICD Tables 20-22).
//!
//! The primary codes are consumed by the `Signal` enum (Phase 1); the secondary
//! codes wait for the E5a-Q pilot / F-NAV tiering (Phase 3) — hence the targeted
//! `allow(dead_code)` on those helpers below.

/// E5a primary code length (chips): 10230 at 10.23 Mcps = 1 ms primary epoch.
pub const E5_PRIMARY_LEN: usize = 10230;

/// E5a-I secondary code length (CS20), one common 20-chip sequence (20 ms).
pub const E5A_I_SECONDARY_LEN: usize = 20;
/// E5a-Q secondary code length (CS100), per-PRN 100-chip sequence (100 ms).
#[allow(dead_code)] // Phase 3 (E5a-Q pilot)
pub const E5A_Q_SECONDARY_LEN: usize = 100;

// 14-bit base-register feedback taps (octal), ICD Table 15. E5a-I and E5a-Q
// share both registers; only base register 2's start value differs per PRN.
const E5A_REG1_TAPS: u16 = 0o40503;
const E5A_REG2_TAPS: u16 = 0o50661;

// Base register 2 start values (octal), ICD Table 16 (E5a-I), PRN n at index n-1.
// Base register 1 starts all-ones for every code.
const E5A_I_REG2_START: [u16; 50] = [
    0o30305, 0o14234, 0o27213, 0o20577, 0o23312, 0o33463, 0o15614, 0o12537, 0o01527, 0o30236,
    0o27344, 0o07272, 0o36377, 0o17046, 0o06434, 0o15405, 0o24252, 0o11631, 0o24776, 0o00630,
    0o11560, 0o17272, 0o27445, 0o31702, 0o13012, 0o14401, 0o34727, 0o22627, 0o30623, 0o27256,
    0o01520, 0o14211, 0o31465, 0o22164, 0o33516, 0o02737, 0o21316, 0o35425, 0o35633, 0o24655,
    0o14054, 0o27027, 0o06604, 0o31455, 0o34465, 0o25273, 0o20763, 0o31721, 0o17312, 0o13277,
];

// Base register 2 start values (octal), ICD Table 17 (E5a-Q), PRN n at index n-1.
const E5A_Q_REG2_START: [u16; 50] = [
    0o25652, 0o05142, 0o24723, 0o31751, 0o27366, 0o24660, 0o33655, 0o27450, 0o07626, 0o01705,
    0o12717, 0o32122, 0o16075, 0o16644, 0o37556, 0o02477, 0o02265, 0o06430, 0o25046, 0o12735,
    0o04262, 0o11230, 0o00037, 0o06137, 0o04312, 0o20606, 0o11162, 0o22252, 0o30533, 0o24614,
    0o07767, 0o32705, 0o05052, 0o27553, 0o03711, 0o02041, 0o34775, 0o05274, 0o37356, 0o16205,
    0o36270, 0o06600, 0o26773, 0o17375, 0o35267, 0o36255, 0o12044, 0o26442, 0o21621, 0o25411,
];

/// One 14-bit Fibonacci LFSR run for [`E5_PRIMARY_LEN`] chips. Output is the
/// j=R (cell 14) bit; the feedback is the parity of the tapped cells and enters
/// cell 1 as the register shifts toward higher index. Tap/start bit conventions
/// per ICD §3.4.1: feedback-tap octal bit j = a_j (j=1..14, a_0 ignored, a_14=1);
/// start-value octal bit (j-1) = s_j (so the octal *is* the cell vector).
fn lfsr_seq(taps_oct: u16, start: u16) -> Vec<u8> {
    let tapmask = (taps_oct >> 1) & 0x3FFF; // a_j placed at bit (j-1)
    let mut reg = start & 0x3FFF;
    let mut out = Vec::with_capacity(E5_PRIMARY_LEN);
    for _ in 0..E5_PRIMARY_LEN {
        out.push(((reg >> 13) & 1) as u8); // output cell j=14
        let fb = (reg & tapmask).count_ones() as u16 & 1;
        reg = ((reg << 1) | fb) & 0x3FFF; // shift up, feedback -> cell 1
    }
    out
}

/// E5a primary code at logic level (0/1) for `prn` (1..=50); `pilot` selects the
/// E5a-Q component, else E5a-I. `None` for an out-of-range PRN.
fn e5a_primary_logic(prn: u8, pilot: bool) -> Option<Vec<u8>> {
    let idx = (prn as usize).checked_sub(1)?;
    let start2 = *if pilot {
        &E5A_Q_REG2_START
    } else {
        &E5A_I_REG2_START
    }
    .get(idx)?;
    let r1 = lfsr_seq(E5A_REG1_TAPS, 0x3FFF); // base register 1: all-ones start
    let r2 = lfsr_seq(E5A_REG2_TAPS, start2);
    Some(r1.iter().zip(r2).map(|(a, b)| a ^ b).collect())
}

/// E5a primary spreading code as bipolar chips (+1/-1) for `prn` (1..=50);
/// `pilot` picks E5a-Q, else E5a-I. Logic 0 -> +1, logic 1 -> -1 (the E1
/// memory-code convention). `None` for an out-of-range PRN.
pub fn e5a_primary_code(prn: u8, pilot: bool) -> Option<Vec<i8>> {
    Some(
        e5a_primary_logic(prn, pilot)?
            .iter()
            .map(|&b| if b == 0 { 1 } else { -1 })
            .collect(),
    )
}

/// E5a-I secondary code (CS20): the common 20-chip sequence (ICD Table 20/22),
/// hex MSB-first, overlaid one chip per 1 ms primary epoch.
const E5A_I_SECONDARY_HEX: &str = "842E9";

/// E5a-Q secondary codes (CS100): per-PRN 100-chip sequences, ICD Tables 20/21
/// assigned CS100_1..50 to E5a-Q PRN 1..50 by Table 22. Hex MSB-first; PRN n at
/// index n-1.
#[allow(dead_code)] // Phase 3 (pilot)
const E5A_Q_SECONDARY_HEX: [&str; 50] = [
    "83F6F69D8F6E15411FB8C9B1C",
    "66558BD3CE0C7792E83350525",
    "59A025A9C1AF0651B779A8381",
    "D3A32640782F7B18E4DF754B7",
    "B91FCAD7760C218FA59348A93",
    "BAC77E933A779140F094FBF98",
    "537785DE280927C6B58BA6776",
    "EFCAB4B65F38531ECA22257E2",
    "79F8CAE838475EA5584BEFC9B",
    "CA5170FEA3A810EC606B66494",
    "1FC32410652A2C49BD845E567",
    "FE0A9A7AFDAC44E42CB95D261",
    "B03062DC2B71995D5AD8B7DBE",
    "F6C398993F598E2DF4235D3D5",
    "1BB2FB8B5BF24395C2EF3C5A1",
    "2F920687D238CC7046EF6AFC9",
    "34163886FC4ED7F2A92EFDBB8",
    "66A872CE47833FB2DFD5625AD",
    "99D5A70162C920A4BB9DE1CA8",
    "81D71BD6E069A7ACCBEDC66CA",
    "A654524074A9E6780DB9D3EC6",
    "C3396A101BEDAF623CFC5BB37",
    "C3D4AB211DF36F2111F2141CD",
    "3DFF25EAE761739265AF145C1",
    "994909E0757D70CDE389102B5",
    "B938535522D119F40C25FDAEC",
    "C71AB549C0491537026B390B7",
    "0CDB8C9E7B53F55F5B0A0597B",
    "61C5FA252F1AF81144766494F",
    "626027778FD3C6BB4BAA7A59D",
    "E745412FF53DEBD03F1C9A633",
    "3592AC083F3175FA724639098",
    "52284D941C3DCAF2721DDB1FD",
    "73B3D8F0AD55DF4FE814ED890",
    "94BF16C83BD7462F6498E0282",
    "A8C3DE1AC668089B0B45B3579",
    "E23FFC2DD2C14388AD8D6BEC8",
    "F2AC871CDF89DDC06B5960D2B",
    "06191EC1F622A77A526868BA1",
    "22D6E2A768E5F35FFC8E01796",
    "25310A06675EB271F2A09EA1D",
    "9F7993C621D4BEC81A0535703",
    "D62999EACF1C99083C0B4A417",
    "F665A7EA441BAA4EA0D01078C",
    "46F3D3043F24CDEABD6F79543",
    "E2E3E8254616BD96CEFCA651A",
    "E548231A82F9A01A19DB5E1B2",
    "265C7F90A16F49EDE2AA706C8",
    "364A3A9EB0F0481DA0199D7EA",
    "9810A7A898961263A0F749F56",
];

/// Decode a hex secondary code into `n_bits` bipolar chips (+1/-1), MSB-first
/// (logic 0 -> +1, 1 -> -1). Trailing bits past `n_bits` (zero-padding the last
/// nibble) are dropped.
fn secondary_code(hex: &str, n_bits: usize) -> Vec<i8> {
    let mut bits = Vec::with_capacity(hex.len() * 4);
    for c in hex.chars() {
        let v = c.to_digit(16).expect("hex secondary code");
        for k in (0..4).rev() {
            bits.push(if (v >> k) & 1 == 0 { 1i8 } else { -1 });
        }
    }
    bits.truncate(n_bits);
    bits
}

/// E5a-I secondary code (CS20) as bipolar chips, common to every PRN.
#[allow(dead_code)] // Phase 3 (tiering)
pub fn e5a_i_secondary_code() -> Vec<i8> {
    secondary_code(E5A_I_SECONDARY_HEX, E5A_I_SECONDARY_LEN)
}

/// E5a-Q secondary code (CS100) as bipolar chips for `prn` (1..=50).
#[allow(dead_code)] // Phase 3 (pilot)
pub fn e5a_q_secondary_code(prn: u8) -> Option<Vec<i8>> {
    let hex = E5A_Q_SECONDARY_HEX.get((prn as usize).checked_sub(1)?)?;
    Some(secondary_code(hex, E5A_Q_SECONDARY_LEN))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ICD first-24-chip hex (Table 16 E5a-I / Table 17 E5a-Q), PRN n at index
    // n-1 -- the published test vectors this whole module is validated against.
    const E5A_I_FIRST24: [&str; 50] = [
        "3CEA9D", "9D8CF1", "45D1C8", "7A0133", "64D423", "23300D", "91CEF2", "AA82DC", "F2A17D",
        "3D84AE", "446D38", "C514F2", "0C0184", "8767E0", "CB8EFF", "93EBCD", "5D55CE", "B19B7C",
        "5805FC", "F99EA1", "B23CE5", "8515E8", "436822", "30F77B", "A7D629", "9BFAC7", "18A25B",
        "69A39F", "39B27D", "454598", "F2BC62", "9DDBC6", "332827", "6E2FCA", "22C6D5", "E881D9",
        "74C4DB", "13AB03", "119323", "594886", "9F4D89", "47A3C0", "C9ED53", "334994", "1B2A30",
        "5513F3", "7831C1", "30B93A", "84D5B4", "A5029C",
    ];
    const E5A_Q_FIRST24: [&str; 50] = [
        "515537", "D67539", "58B2E5", "305914", "442710", "593CF8", "214AD7", "435EA6", "C1A7D5",
        "F0E94A", "A8C239", "2EB63B", "8F0A46", "896DD4", "0245F1", "EB0160", "ED28B3", "CB9F5B",
        "576592", "A88811", "DD3649", "B59F42", "FF81F6", "CE8128", "DCD55C", "79E450", "B63460",
        "6D562B", "3A9010", "59CD72", "C0211A", "28EB96", "D7554B", "425126", "E0DAFB", "EF79F2",
        "18085D", "D50CD8", "0447B9", "8DE877", "0D1FA0", "C9FCF7", "48116D", "840BCC", "152004",
        "0D4897", "AF6D25", "4B7593", "71BB1B", "53DA0E",
    ];

    /// Pack the first 24 logic chips MSB-first into 6 hex nibbles.
    fn first24_hex(logic: &[u8]) -> String {
        (0..6)
            .map(|nib| {
                let v = (0..4).fold(0u8, |acc, k| (acc << 1) | logic[nib * 4 + k]);
                char::from_digit(v as u32, 16).unwrap().to_ascii_uppercase()
            })
            .collect()
    }

    // The gold-standard validation: the generated code's first 24 chips must
    // equal the ICD's published hex for every PRN, both components. This pins the
    // LFSR convention (taps, start mapping, output cell, shift) and every start
    // value at once -- if any were wrong, a PRN would mismatch.
    #[test]
    fn e5a_primary_matches_icd_first_chips() {
        for prn in 1..=50u8 {
            let i = e5a_primary_logic(prn, false).unwrap();
            assert_eq!(i.len(), E5_PRIMARY_LEN, "E5a-I PRN{prn} length");
            assert_eq!(
                first24_hex(&i),
                E5A_I_FIRST24[prn as usize - 1],
                "E5a-I PRN{prn} first 24 chips"
            );
            let q = e5a_primary_logic(prn, true).unwrap();
            assert_eq!(q.len(), E5_PRIMARY_LEN, "E5a-Q PRN{prn} length");
            assert_eq!(
                first24_hex(&q),
                E5A_Q_FIRST24[prn as usize - 1],
                "E5a-Q PRN{prn} first 24 chips"
            );
        }
    }

    // A length-10230 truncated, combined M-sequence is bipolar and near-balanced.
    #[test]
    fn e5a_primary_is_bipolar_and_balanced() {
        for &pilot in &[false, true] {
            let c = e5a_primary_code(7, pilot).unwrap();
            assert_eq!(c.len(), E5_PRIMARY_LEN);
            assert!(c.iter().all(|&x| x == 1 || x == -1));
            let sum: i32 = c.iter().map(|&x| x as i32).sum();
            assert!(
                sum.abs() < 300,
                "near-balanced, got sum {sum} (pilot={pilot})"
            );
        }
    }

    #[test]
    fn e5a_secondary_codes_decode() {
        let cs20 = e5a_i_secondary_code();
        assert_eq!(cs20.len(), E5A_I_SECONDARY_LEN);
        assert!(cs20.iter().all(|&x| x == 1 || x == -1));
        for prn in 1..=50u8 {
            let cs100 = e5a_q_secondary_code(prn).unwrap();
            assert_eq!(cs100.len(), E5A_Q_SECONDARY_LEN, "PRN{prn} CS100 length");
        }
        assert!(e5a_q_secondary_code(51).is_none());
    }

    #[test]
    fn out_of_range_prn_is_none() {
        assert!(e5a_primary_code(0, false).is_none());
        assert!(e5a_primary_code(51, false).is_none());
    }
}
